name: twafok_cli
description: CLI tool for Twafok project clean architecture - Generate features, usecases, DI and barrel files automatically
version: 1.0.1
homepage: https://github.com/muhamaadessam/twafok_cli
repository: https://github.com/muhamaadessam/twafok_cli
issue_tracker: https://github.com/muhamaadessam/twafok_cli/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  twafok: twafok_cli  # عشان تقدر تكتب twafok بدل twafok_cli

dependencies:
  args: ^2.4.0
  path: ^1.9.0
  io: ^1.0.4

dev_dependencies:
  lints: ^3.0.0